In [38]:
import numpy as np
from tensorflow.keras.utils import to_categorical

In [40]:
raw_text = '''
Hey, I was doing just fine before I met you
I drink too much and that's an issue, but I'm okay
Hey, you tell your friends it was nice to meet them
But I hope I never see them again
I know it breaks your heart
Moved to the city in a broke-down car, and
Four years, no calls
Now you're looking pretty in a hotel bar
And I, I, I, I, I can't stop
No, I, I, I, I, I can't stop
So, baby, pull me closer
In the back seat of your Rover
That I know you can't afford
Bite that tattoo on your shoulder
Pull the sheets right off the corner
Of that mattress that you stole
From your roommate back in Boulder
We ain't ever getting older
We ain't ever getting older
We ain't ever getting older
You look as good as the day I met you
I forget just why I left you, I was insane
Stay and play that Blink-182 song
That we beat to death in Tucson, okay
I know it breaks your heart
Moved to the city in a broke-down car, and
Four years, no call
Now I'm looking pretty in a hotel bar
And I, I, I, I, I can't stop
No, I, I, I, I, I can't stop
So, baby, pull me closer
In the back seat of your Rover
That I know you can't afford
Bite that tattoo on your shoulder
Pull the sheets right off the corner
Of that mattress that you stole
From your roommate back in Boulder
We ain't ever getting older
We ain't ever getting older
We ain't ever getting older
'''

In [41]:
tokens = raw_text.split()
raw_text = ' '.join(tokens)
print(raw_text)

Hey, I was doing just fine before I met you I drink too much and that's an issue, but I'm okay Hey, you tell your friends it was nice to meet them But I hope I never see them again I know it breaks your heart Moved to the city in a broke-down car, and Four years, no calls Now you're looking pretty in a hotel bar And I, I, I, I, I can't stop No, I, I, I, I, I can't stop So, baby, pull me closer In the back seat of your Rover That I know you can't afford Bite that tattoo on your shoulder Pull the sheets right off the corner Of that mattress that you stole From your roommate back in Boulder We ain't ever getting older We ain't ever getting older We ain't ever getting older You look as good as the day I met you I forget just why I left you, I was insane Stay and play that Blink-182 song That we beat to death in Tucson, okay I know it breaks your heart Moved to the city in a broke-down car, and Four years, no call Now I'm looking pretty in a hotel bar And I, I, I, I, I can't stop No, I, I, 

In [42]:
char_vocab = sorted(list(set(raw_text)))
vocab_size = len(char_vocab)
print('문자집합 : ', char_vocab)
print('문자 집합의 크기 : {}'.format(vocab_size))

문자집합 :  [' ', "'", ',', '-', '1', '2', '8', 'A', 'B', 'F', 'H', 'I', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'W', 'Y', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'y']
문자 집합의 크기 : 44


In [43]:
char_to_index = dict((char, index) for index, char in enumerate(char_vocab))
print(char_to_index)

{' ': 0, "'": 1, ',': 2, '-': 3, '1': 4, '2': 5, '8': 6, 'A': 7, 'B': 8, 'F': 9, 'H': 10, 'I': 11, 'M': 12, 'N': 13, 'O': 14, 'P': 15, 'R': 16, 'S': 17, 'T': 18, 'W': 19, 'Y': 20, 'a': 21, 'b': 22, 'c': 23, 'd': 24, 'e': 25, 'f': 26, 'g': 27, 'h': 28, 'i': 29, 'j': 30, 'k': 31, 'l': 32, 'm': 33, 'n': 34, 'o': 35, 'p': 36, 'r': 37, 's': 38, 't': 39, 'u': 40, 'v': 41, 'w': 42, 'y': 43}


In [44]:
length = 11
sequences = []
for i in range(length, len(raw_text)):
  seq = raw_text[i-length:i]
  sequences.append(seq)
print('샘플의 수 : %d' %len(sequences))

샘플의 수 : 1314


In [45]:
sequences [:30]

['Hey, I was ',
 'ey, I was d',
 'y, I was do',
 ', I was doi',
 ' I was doin',
 'I was doing',
 ' was doing ',
 'was doing j',
 'as doing ju',
 's doing jus',
 ' doing just',
 'doing just ',
 'oing just f',
 'ing just fi',
 'ng just fin',
 'g just fine',
 ' just fine ',
 'just fine b',
 'ust fine be',
 'st fine bef',
 't fine befo',
 ' fine befor',
 'fine before',
 'ine before ',
 'ne before I',
 'e before I ',
 ' before I m',
 'before I me',
 'efore I met',
 'fore I met ']

In [46]:
encoded_sequences = []
for sequence in sequences:
  encoded_sequence = [char_to_index[char] for char in sequence]
  encoded_sequences.append(encoded_sequence)

In [47]:
encoded_sequences[:10]

[[10, 25, 43, 2, 0, 11, 0, 42, 21, 38, 0],
 [25, 43, 2, 0, 11, 0, 42, 21, 38, 0, 24],
 [43, 2, 0, 11, 0, 42, 21, 38, 0, 24, 35],
 [2, 0, 11, 0, 42, 21, 38, 0, 24, 35, 29],
 [0, 11, 0, 42, 21, 38, 0, 24, 35, 29, 34],
 [11, 0, 42, 21, 38, 0, 24, 35, 29, 34, 27],
 [0, 42, 21, 38, 0, 24, 35, 29, 34, 27, 0],
 [42, 21, 38, 0, 24, 35, 29, 34, 27, 0, 30],
 [21, 38, 0, 24, 35, 29, 34, 27, 0, 30, 40],
 [38, 0, 24, 35, 29, 34, 27, 0, 30, 40, 38]]

In [48]:
encoded_sequences = np.array(encoded_sequences)

x_data = encoded_sequences[:,:-1]
y_data = encoded_sequences[:,-1]

In [49]:
print(x_data[:5])

[[10 25 43  2  0 11  0 42 21 38]
 [25 43  2  0 11  0 42 21 38  0]
 [43  2  0 11  0 42 21 38  0 24]
 [ 2  0 11  0 42 21 38  0 24 35]
 [ 0 11  0 42 21 38  0 24 35 29]]


In [50]:
print(y_data[:5])

[ 0 24 35 29 34]


In [51]:
x_data_one_hot = [to_categorical(encoded, num_classes=vocab_size) for encoded in x_data]
x_data_one_hot = np.array(x_data_one_hot)
y_data_one_hot = to_categorical(y_data, num_classes=vocab_size)

In [52]:
print(x_data_one_hot.shape)

(1314, 10, 44)


In [53]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from tensorflow.keras.preprocessing.sequence import pad_sequences

hidden_units = 64

model = Sequential()
model.add(LSTM(hidden_units, input_shape=(x_data_one_hot.shape[1], x_data_one_hot.shape[2])))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_data_one_hot, y_data_one_hot, epochs=200, verbose=2)

Epoch 1/200
42/42 - 2s - loss: 3.5412 - accuracy: 0.1834 - 2s/epoch - 58ms/step
Epoch 2/200
42/42 - 0s - loss: 3.0444 - accuracy: 0.2078 - 302ms/epoch - 7ms/step
Epoch 3/200
42/42 - 0s - loss: 2.9905 - accuracy: 0.2078 - 309ms/epoch - 7ms/step
Epoch 4/200
42/42 - 0s - loss: 2.9563 - accuracy: 0.2078 - 292ms/epoch - 7ms/step
Epoch 5/200
42/42 - 0s - loss: 2.9246 - accuracy: 0.2078 - 293ms/epoch - 7ms/step
Epoch 6/200
42/42 - 0s - loss: 2.8726 - accuracy: 0.2078 - 300ms/epoch - 7ms/step
Epoch 7/200
42/42 - 0s - loss: 2.8204 - accuracy: 0.2116 - 297ms/epoch - 7ms/step
Epoch 8/200
42/42 - 0s - loss: 2.7446 - accuracy: 0.2146 - 298ms/epoch - 7ms/step
Epoch 9/200
42/42 - 0s - loss: 2.6942 - accuracy: 0.2359 - 309ms/epoch - 7ms/step
Epoch 10/200
42/42 - 0s - loss: 2.6184 - accuracy: 0.2679 - 294ms/epoch - 7ms/step
Epoch 11/200
42/42 - 0s - loss: 2.5562 - accuracy: 0.2785 - 293ms/epoch - 7ms/step
Epoch 12/200
42/42 - 0s - loss: 2.5011 - accuracy: 0.3082 - 287ms/epoch - 7ms/step
Epoch 13/200
42

In [54]:
def sentence_generation(model, char_to_index, seq_length, seed_text, n):
  init_text = seed_text
  sentence=''

  for _ in range(n):
    encoded = [char_to_index[char] for char in seed_text]
    encoded = pad_sequences([encoded], maxlen=seq_length, padding='pre')
    encoded = to_categorical(encoded, num_classes=len(char_to_index))

    result = model.predict(encoded, verbose=0)
    result = np.argmax(result, axis=1)

    for char, index in char_to_index.items():
      if index == result:
        break

    seed_text = seed_text + char
    sentence = sentence + char

  sentence = init_text + sentence
  return sentence

In [59]:
print(sentence_generation(model, char_to_index, 10, 'You look as g', 80))

You look as good as the day I met you I drink too much and that's an issue, but I'm okay Hey,
